### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Yaretzi01** [SistemasTecTlaxiaco/infografia-Yaretzi01#1]
![Infografia](https://user-images.githubusercontent.com/60899757/153694851-d5d1329e-e7ba-4120-a32d-7c3a17ff0263.png)

**Comment by claudiasilvavenda** [comment]
La infografía cumple con lo que pide la rubrica.
la calif. es 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
